### ISSUE TITLE
Circular dependency between Button & ButtonInput?

### ISSUE THREAD

**Issue by michaeljones** [react-bootstrap/react-bootstrap#1428]
Hi,

I'm getting the following error having updated to 0.27.2 from 0.23.7.

```
TypeError: Cannot read property 'types' of undefined
    at Object.<anonymous> (/home/mike/root/projects/hive/portal/node_modules/react-bootstrap/lib/Button.js:54:70)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mike/root/projects/hive/portal/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mike/root/projects/hive/portal/node_modules/react-bootstrap/lib/ButtonInput.js:19:15)
    at Module._compile (module.js:460:26)
```

I'm trying to understand what might be going on. I feel like it might be a circular import issue as Button & ButtonInput import each other which can be an issue. That said, I've no idea why others might not be experiencing this problem which makes me feel like it is something in my set up. I am getting this error from a `express-react-views` set up rather than compiling into a client side bundle.

I'm using:
- babel **5.8.23**
- express-react-views **0.9.0**
- react **0.14.0**

I'm on Ubuntu 14.04. 

My understanding of circular imports in node is limited but I feel like they aren't a great idea though in some situations the problems can be mitigated by extra code as explained here: https://coderwall.com/p/myzvmg/circular-dependencies-in-node-js

Might be wrong about the whole thing though. Any help would be much appreciated. Thank you for working on and sharing this project. I've finding it extremely useful.

Cheers,
Michael

**Comment by taion** [comment]
Yup, that's definitely not ideal. Thanks for the PR.
