### ISSUE TITLE
ServerSideRendering throws error "ReferenceError: navigator is not defined"

### ISSUE THREAD

**Issue by veeramarni** [react-bootstrap/react-bootstrap#2131]
I was using meteor 1.4 version and using react-bootstrap which works fine when the page rendered directly  in the browser but when i try to do server side rendering i get following error. 

But if i remove all the components related to `react-bootstrap' it renders without error. 

```

ReferenceError: navigator is not defined
    at webpack:///server.js:12:1
    at webpack:///server.js:9:1
    at Object.<anonymous> (webpack:///server.js:9:1)
    at t (webpack:///server.js:4:1)
    at webpack:///server.js:42:1
    at Object.<anonymous> (webpack:///server.js:42:1)
    at t (webpack:///server.js:4:1)
    at Object.e.__esModule.default (webpack:///server.js:41:1)
    at t (webpack:///server.js:4:1)
    at Object.e.__esModule.default (webpack:///server.js:41:1)
Exited with code: 1
Your application is crashing. Waiting for file change.
```

**Comment by taion** [comment]
This package doesn't use `navigator` at all. You can see that the only hit to it in the code is on the docs page, which isn't shipped.
