### ISSUE TITLE
 unable to build react-bootstrap

### ISSUE THREAD

**Issue by Evanion** [react-bootstrap/react-bootstrap#2148]
`````
# npm run build

> react-bootstrap@0.30.2 build /Users/mikael/Projects/Personliga/react-bootstrap
> babel-node tools/build-cli.js

Building: npm module
Building: es module
Building: bower module
Building: distributable
Building: docs
Error: Cannot remove "babel-plugin-transform-es2015-modules-commonjs" from the plugin list.
    at Object.<anonymous> (/Users/mikael/Projects/Personliga/react-bootstrap/node_modules/babel-preset-es2015-webpack/index.js:35:11)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mikael/Projects/Personliga/react-bootstrap/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/mikael/Projects/Personliga/react-bootstrap/node_modules/modify-babel-preset/index.js:35:23)
`````
There is a change in a newer version of bable that requires some changed to the `babel-preset-es2015-webpack` and `babel-preset-es2015` implementation. See the deprication notice [on their repo](https://github.com/gajus/babel-preset-es2015-webpack).

Versions:
node: 6.3.1
npm: 3.10.6

**Comment by taion** [comment]
Indeed, and we were part of driving that – but we need a new babel-standalone release first.

**Comment by Evanion** [comment]
ok, any idea when that might be expeced? Do they have any specific release cycle?
