### ISSUE TITLE
Jest tests not working with create-react-app scaffolding

### ISSUE THREAD

**Issue by cguckes** [react-bootstrap/react-bootstrap#2747]
Once I add react-bootstrap to the project, I get the following error when I try to run `npm test`

```
FAIL  src/App.test.js
  ● Test suite failed to run

    /home/chris/torq-dev/git/hotelmanager/code/frontend/node_modules/react-bootstrap/es/Panel.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _Object$values from 'babel-runtime/core-js/object/values';
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
      at Object.<anonymous> (src/views/ButtonGridView.jsx:2:14)
      at Object.<anonymous> (src/App.js:4:23)

Test Suites: 2 failed, 2 passed, 4 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        0.137s, estimated 1s
Ran all test suites related to changed files.
```

Am I missing something or is react-bootstrap not compatible with create-react-app?

**Comment by taion** [comment]
This looks like something misconfigured upstream. Please open an issue there.
