### ISSUE TITLE
build fails due to missing babel packages

### ISSUE THREAD

**Issue by jharris4** [react-bootstrap/react-bootstrap#2831]
If I do the following:

```
cd /Source
git clone https://github.com/react-bootstrap/react-bootstrap.git
cd react-bootstrap
yarn install
yarn build
```

I get the following error:

```
ReferenceError: Unknown plugin "transform-es3-member-expression-literals" specified in "base" at 2, attempted to resolve relative to "/Source/react-bootstrap/src"
    at /Source/react-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Source/react-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Source/react-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Source/react-bootstrap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Source/react-bootstrap/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Source/react-bootstrap/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Source/react-bootstrap/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at buildContent (/Source/react-bootstrap/tools/buildBabel.js:8:18)
    at buildFile (/Source/react-bootstrap/tools/buildBabel.js:18:5)
```

The same error arises when installing with npm instead of yarn as well.

It seems that some of the build scripts include babel presets/plugins that are not included in package.json, like this file: https://github.com/react-bootstrap/react-bootstrap/blob/0e93f934e426685c6570ac63aacd8fae6cacafda/tools/es/build.js

I was able to fix the errors by adding the following to package.json under "devDependencies":

```
"babel-plugin-transform-es3-member-expression-literals": "^6.22.0",
"babel-plugin-transform-es3-property-literals": "^6.22.0",
"babel-preset-es2015": "^6.24.1",
"babel-preset-stage-1": "^6.24.1",
```

Was it just an oversight that these packages were not included?

**Comment by fumblehool** [comment]
@taion Can I work on this issue?

**Comment by jquense** [comment]
Go for it @fumblehool. You should just need to copy the babelrc  into that build script
