### ISSUE TITLE
Resizing window with Modal showing throws error in Safari 11 with React 16

### ISSUE THREAD

**Issue by jharris4** [react-bootstrap/react-bootstrap#2842]
I'm seeing the following error when resizing the browser window with Safari 11:

```
TypeError: null is not an object (evaluating 'this._modal.getDialogElement')
at updateStyle(/node_modules/react-bootstrap/es/Modal.js:199:0)
at handleWindowResize(/node_modules/react-bootstrap/es/Modal.js:183:0)
```

This is with `react-bootstrap 0.31.3` `react-overlays 0.7.3` and `react 16.0.0`.

It works fine in Chrome

**Comment by jharris4** [comment]
I did some further debugging, and the Modal class is using a `ref` callback as a prop to `react-overlays/Modal` on this line: https://github.com/react-bootstrap/react-bootstrap/blob/0e93f934e426685c6570ac63aacd8fae6cacafda/src/Modal.js#L235

```
ref={(c) => { this._modal = c; }}
```

And I changed to do some debug logging like so:

```
ref={(c) => { console.log('set modal ref to: ', c); this._modal = c; }}
```

When I reproduce the error in Safari 11 (by resizing the window a bunch of times in a row), I'm seeing log output like the following:

```
[Log] set modal ref to:  – null
[Log] set modal ref to:  – Modal {props: Object, context: {}, refs: {}, …}
[Log] set modal ref to:  – null
[Log] set modal ref to:  – Modal {props: Object, context: {}, refs: {}, …} 
[Log] set modal ref to:  – null
[Log] set modal ref to:  – Modal {props: Object, context: {}, refs: {}, …}
[Log] set modal ref to:  – null
[Log] set modal ref to:  – null
[Error] TypeError: null is not an object (evaluating 'this._modal.getDialogElement')
```

So it seems like the bug is triggered when Safari 11 somehow passes a null `ref` back twice and a row.

I checked this against Chrome, and I never saw double null refs there.
