### ISSUE TITLE
Panel - Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Shadowman4205** [react-bootstrap/react-bootstrap#2959]
Hello trying to use panel but getting this error

```
TypeError: Cannot read property 'toLowerCase' of undefined
    at ReactDOMServerRenderer.renderDOM (...\node_modules\react-dom\cjs\react-dom-server.node.development.js:2776:27)
    at ReactDOMServerRenderer.render (...\node_modules\react-dom\cjs\react-dom-server.node.development.js:2755:23)
    at ReactDOMServerRenderer.read (...\node_modules\react-dom\cjs\react-dom-server.node.development.js:2722:19)
    at Object.renderToString (...\node_modules\react-dom\cjs\react-dom-server.node.development.js:2980:25)
    at ...\src\server.js:238:1
    at Generator.next (<anonymous>)
    at step (...\build\server.js:49313:191)
    at ...\build\server.js:49313:361
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:208:7)
```

**Comment by taion** [comment]
There's nothing to go off of here.
