### ISSUE TITLE
Navbar example with <NavDropdown.Divider /> throws exception

### ISSUE THREAD

**Issue by ElPatricio** [react-bootstrap/react-bootstrap#3491]
I copied [this responsive Navbar example](https://react-bootstrap.github.io/components/navbar/#navbars-mobile-friendly) from the components documentation and I receive the exception below. The exception disappears when I remove `<NavDropdown.Divider />`.

**./src/App.js**
```
import React, { Component } from 'react';
import Dnavi from './Dnavi/Dnavi';

class App extends Component {
  render() {
    return (
      <div className="App">
        <Dnavi/>
      </div>
    );
  }
}

export default App;
```

**./src/Dnavi/Dnavi.js**
```
import React from 'react';
import Navbar from 'react-bootstrap/Navbar';
import Nav from 'react-bootstrap/Nav';
import NavDropdown from 'react-bootstrap/Nav';

const dnavi = (props) => {
    return (
      <Navbar collapseOnSelect expand="lg" bg="dark" variant="dark">
      <Navbar.Brand href="#home">React-Bootstrap</Navbar.Brand>
      <Navbar.Toggle aria-controls="responsive-navbar-nav" />
      <Navbar.Collapse id="responsive-navbar-nav">
        <Nav className="mr-auto">
          <Nav.Link href="#features">Features</Nav.Link>
          <Nav.Link href="#pricing">Pricing</Nav.Link>
          <NavDropdown title="Dropdown" id="collasible-nav-dropdown">
            <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
            <NavDropdown.Item href="#action/3.2">Another action</NavDropdown.Item>
            <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
            <NavDropdown.Divider />
            <NavDropdown.Item href="#action/3.4">Separated link</NavDropdown.Item>
          </NavDropdown>
        </Nav>
        <Nav>
          <Nav.Link href="#deets">More deets</Nav.Link>
          <Nav.Link eventKey={2} href="#memes">
            Dank memes
          </Nav.Link>
        </Nav>
      </Navbar.Collapse>
    </Navbar>
    )
};

export default dnavi;
```

**./src/index.js**
```
import 'bootstrap/dist/css/bootstrap.min.css';
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(<App />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: http://bit.ly/CRA-PWA
serviceWorker.unregister();
```
**package.json**
```
{
  "name": "consilio-ui",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "bootstrap": "^4.3.1",
    "react": "^16.8.1",
    "react-bootstrap": "^1.0.0-beta.5",
    "react-dom": "^16.8.1",
    "react-scripts": "2.1.5",
    "typescript": "^3.3.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
```

**Exception log**
```
index.js:1446 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at Dnavi.js:19.
    in dnavi (at App.js:8)
    in div (at App.js:7)
    in App (at src/index.js:8)
function.console.(anonymous function) @ index.js:1446
warningWithoutStack @ react.development.js:188
warning @ react.development.js:623
createElementWithValidation @ react.development.js:1785
dnavi @ Dnavi.js:19
renderWithHooks @ react-dom.development.js:13261
mountIndeterminateComponent @ react-dom.development.js:15265
beginWork @ react-dom.development.js:15816
performUnitOfWork @ react-dom.development.js:19745
workLoop @ react-dom.development.js:19786
renderRoot @ react-dom.development.js:19866
performWorkOnRoot @ react-dom.development.js:20811
performWork @ react-dom.development.js:20721
performSyncWork @ react-dom.development.js:20695
requestWork @ react-dom.development.js:20550
scheduleWork @ react-dom.development.js:20357
scheduleRootUpdate @ react-dom.development.js:21061
updateContainerAtExpirationTime @ react-dom.development.js:21087
updateContainer @ react-dom.development.js:21155
ReactRoot.render @ react-dom.development.js:21468
(anonymous) @ react-dom.development.js:21620
unbatchedUpdates @ react-dom.development.js:20938
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21616
render @ react-dom.development.js:21691
(anonymous) @ index.js:8
./src/index.js @ main.chunk.js:57
__webpack_require__ @ bundle.js:782
fn @ bundle.js:150
0 @ main.chunk.js:81
__webpack_require__ @ bundle.js:782
checkDeferredModules @ bundle.js:46
webpackJsonpCallback @ bundle.js:33
(anonymous) @ main.chunk.js:1
react-dom.development.js:57 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `dnavi`.
    at invariant (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:57:19)
    at createFiberFromTypeAndProps (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:10531:15)
    at createFiberFromElement (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:10551:19)
    at createChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12350:32)
    at reconcileChildrenArray (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12619:29)
    at reconcileChildFibers (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12969:18)
    at reconcileChildren (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14627:32)
    at updateHostComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15105:7)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15847:18)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19745:16)
    at workLoop (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19786:28)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:147:18)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:196:20)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:250:35)
    at replayUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18976:9)
    at renderRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19899:17)
    at performWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20811:11)
    at performWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20721:11)
    at performSyncWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20695:7)
    at requestWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20550:9)
    at scheduleWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20357:9)
    at scheduleRootUpdate (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21061:7)
    at updateContainerAtExpirationTime (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21087:14)
    at updateContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21155:14)
    at ReactRoot.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21468:7)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21620:18)
    at unbatchedUpdates (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20938:14)
    at legacyRenderSubtreeIntoContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21616:9)
    at Object.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21691:16)
    at eval (webpack-internal:///./src/index.js:19:50)
    at Module../src/index.js (http://localhost:3000/static/js/main.chunk.js:57:1)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:782:30)
    at fn (http://localhost:3000/static/js/bundle.js:150:20)
    at Object.0 (http://localhost:3000/static/js/main.chunk.js:81:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:782:30)
    at checkDeferredModules (http://localhost:3000/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost:3000/static/js/bundle.js:33:19)
    at http://localhost:3000/static/js/main.chunk.js:1:57
invariant @ react-dom.development.js:57
createFiberFromTypeAndProps @ react-dom.development.js:10531
createFiberFromElement @ react-dom.development.js:10551
createChild @ react-dom.development.js:12350
reconcileChildrenArray @ react-dom.development.js:12619
reconcileChildFibers @ react-dom.development.js:12969
reconcileChildren @ react-dom.development.js:14627
updateHostComponent @ react-dom.development.js:15105
beginWork @ react-dom.development.js:15847
performUnitOfWork @ react-dom.development.js:19745
workLoop @ react-dom.development.js:19786
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
replayUnitOfWork @ react-dom.development.js:18976
renderRoot @ react-dom.development.js:19899
performWorkOnRoot @ react-dom.development.js:20811
performWork @ react-dom.development.js:20721
performSyncWork @ react-dom.development.js:20695
requestWork @ react-dom.development.js:20550
scheduleWork @ react-dom.development.js:20357
scheduleRootUpdate @ react-dom.development.js:21061
updateContainerAtExpirationTime @ react-dom.development.js:21087
updateContainer @ react-dom.development.js:21155
ReactRoot.render @ react-dom.development.js:21468
(anonymous) @ react-dom.development.js:21620
unbatchedUpdates @ react-dom.development.js:20938
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21616
render @ react-dom.development.js:21691
(anonymous) @ index.js:8
./src/index.js @ main.chunk.js:57
__webpack_require__ @ bundle.js:782
fn @ bundle.js:150
0 @ main.chunk.js:81
__webpack_require__ @ bundle.js:782
checkDeferredModules @ bundle.js:46
webpackJsonpCallback @ bundle.js:33
(anonymous) @ main.chunk.js:1
index.js:1446 The above error occurred in the <div> component:
    in div (created by AbstractNav)
    in AbstractNav (created by Context.Consumer)
    in ForwardRef(ContextTransform(AbstractNav)) (created by Nav)
    in Nav (created by Context.Consumer)
    in ForwardRef(Bootstrap(Nav)) (created by Uncontrolled(Component))
    in Uncontrolled(Component) (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in ForwardRef(ContextTransform) (at Dnavi.js:15)
    in div (created by AbstractNav)
    in AbstractNav (created by Context.Consumer)
    in ForwardRef(ContextTransform(AbstractNav)) (created by Nav)
    in Nav (created by Context.Consumer)
    in ForwardRef(Bootstrap(Nav)) (created by Uncontrolled(Component))
    in Uncontrolled(Component) (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in ForwardRef(ContextTransform) (at Dnavi.js:12)
    in div (created by Context.Consumer)
    in Transition (created by Collapse)
    in Collapse (created by Context.Consumer)
    in NavbarCollapse (created by Context.Consumer)
    in ForwardRef(Bootstrap(NavbarCollapse)) (at Dnavi.js:11)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (created by ForwardRef)
    in ForwardRef (created by Context.Consumer)
    in ForwardRef(Bootstrap(undefined)) (at Dnavi.js:8)
    in dnavi (at App.js:8)
    in div (at App.js:7)
    in App (at src/index.js:8)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
function.console.(anonymous function) @ index.js:1446
logCapturedError @ react-dom.development.js:17401
logError @ react-dom.development.js:17437
update.callback @ react-dom.development.js:18452
callCallback @ react-dom.development.js:16648
commitUpdateEffects @ react-dom.development.js:16688
commitUpdateQueue @ react-dom.development.js:16678
commitLifeCycles @ react-dom.development.js:17693
commitAllLifeCycles @ react-dom.development.js:19141
callCallback @ react-dom.development.js:147
invokeGuardedCallbackDev @ react-dom.development.js:196
invokeGuardedCallback @ react-dom.development.js:250
commitRoot @ react-dom.development.js:19360
completeRoot @ react-dom.development.js:20893
performWorkOnRoot @ react-dom.development.js:20816
performWork @ react-dom.development.js:20721
performSyncWork @ react-dom.development.js:20695
requestWork @ react-dom.development.js:20550
scheduleWork @ react-dom.development.js:20357
scheduleRootUpdate @ react-dom.development.js:21061
updateContainerAtExpirationTime @ react-dom.development.js:21087
updateContainer @ react-dom.development.js:21155
ReactRoot.render @ react-dom.development.js:21468
(anonymous) @ react-dom.development.js:21620
unbatchedUpdates @ react-dom.development.js:20938
legacyRenderSubtreeIntoContainer @ react-dom.development.js:21616
render @ react-dom.development.js:21691
(anonymous) @ index.js:8
./src/index.js @ main.chunk.js:57
__webpack_require__ @ bundle.js:782
fn @ bundle.js:150
0 @ main.chunk.js:81
__webpack_require__ @ bundle.js:782
checkDeferredModules @ bundle.js:46
webpackJsonpCallback @ bundle.js:33
(anonymous) @ main.chunk.js:1
react-dom.development.js:57 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `dnavi`.
    at invariant (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:57:19)
    at createFiberFromTypeAndProps (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:10531:15)
    at createFiberFromElement (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:10551:19)
    at createChild (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12350:32)
    at reconcileChildrenArray (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12619:29)
    at reconcileChildFibers (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12969:18)
    at reconcileChildren (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14627:32)
    at updateHostComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15105:7)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15847:18)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19745:16)
    at workLoop (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19786:28)
    at renderRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:19866:11)
    at performWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20811:11)
    at performWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20721:11)
    at performSyncWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20695:7)
    at requestWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20550:9)
    at scheduleWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20357:9)
    at scheduleRootUpdate (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21061:7)
    at updateContainerAtExpirationTime (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21087:14)
    at updateContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21155:14)
    at ReactRoot.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21468:7)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21620:18)
    at unbatchedUpdates (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:20938:14)
    at legacyRenderSubtreeIntoContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21616:9)
    at Object.render (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21691:16)
    at eval (webpack-internal:///./src/index.js:19:50)
    at Module../src/index.js (http://localhost:3000/static/js/main.chunk.js:57:1)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:782:30)
    at fn (http://localhost:3000/static/js/bundle.js:150:20)
    at Object.0 (http://localhost:3000/static/js/main.chunk.js:81:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:782:30)
    at checkDeferredModules (http://localhost:3000/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost:3000/static/js/bundle.js:33:19)
    at http://localhost:3000/static/js/main.chunk.js:1:57
```

**Comment by ElPatricio** [comment]
Typo

**Comment by ericjohannsen** [comment]
If only you said what the typo _was_, you might have helped me solve the same problem...
