### ISSUE TITLE
Cannot find module `../../lib/Navbar`

### ISSUE THREAD

**Issue by RichardLitt** [react-bootstrap/react-bootstrap#435]
I'm not sure what the deal is here - there doesn't seem to be a `lib` folder for `docs/src/NavMain.js` to require from. Am I missing something? 

```sh
09:54 ~/src/react-bootstrap/docs $ npm install
npm WARN package.json react-bootstrap-docs@0.0.0 No repository field.
09:54 ~/src/react-bootstrap/docs $ npm run build

> react-bootstrap-docs@0.0.0 build /Users/richard/src/react-bootstrap/docs
> node build.js && browserify client.js | uglifyjs -cm 2>/dev/null > ./assets/bundle.js

module.js:338
    throw err;
          ^
Error: Cannot find module '../../lib/Navbar'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/richard/src/react-bootstrap/docs/src/NavMain.js:5:14)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/richard/src/react-bootstrap/docs/node_modules/node-jsx/index.js:26:12)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by RichardLitt** [comment]
Looks like this is an issue with `lib` being renamed to `src`. I changed it, but then I ran into more issues. I'm running node v0.12, and `require('fileName')` doesn't work if `fileName` is a .jsx file - I have to manually change all of these instances to `require('fileName.jsx')`. 

I'm still trying to run `npm run build`, and then I run into this issue:

```js
  render: function () {
    var {
        disabled,
        active,
        href,
        title,
        target,
        children,
        ...props } = this.props,
        classes = {
          'active': active,
          'disabled': disabled
        };
```
```sh
10:06 ~/src/react-bootstrap/docs $ npm run build

> react-bootstrap-docs@0.0.0 build /Users/richard/src/react-bootstrap/docs
> node build.js && browserify client.js | uglifyjs -cm 2>/dev/null > ./assets/bundle.js

/Users/richard/src/react-bootstrap/src/NavItem.jsx:26
    var {
        ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/richard/src/react-bootstrap/docs/node_modules/node-jsx/index.js:26:12)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/richard/src/react-bootstrap/docs/src/ReactPlayground.js:24:15)
    at Module._compile (module.js:460:26)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/richard/src/react-bootstrap/docs/node_modules/node-jsx/index.js:26:12)
```

I feel like I'm missing something - am I building this wrong?

**Comment by mtscout6** [comment]
Did you run `grunt build` from the repo root before working with the docs?

**Comment by yumingcao-okta** [comment]
Just for record, for me this error is caused by mistype with capital B in `NavBar`. It had been working on my local env and not happy on CI.
