### ISSUE TITLE
TypeScript error when defining a ref on Button

### ISSUE THREAD

**Issue by kumar303** [react-bootstrap/react-bootstrap#4706]
## Describe the bug

I have no idea how to type a `ref` attribute for `Button`. Every value I can think of produces a compilation error.

## To Reproduce

1. Check out https://github.com/react-bootstrap/react-bootstrap/commit/68127cbe67338cdc24f83dc66f869f9bfc875aaa
2. Apply the following patch

```diff
diff --git a/types/simple.test.tsx b/types/simple.test.tsx
index 1a04a92e..bcd8b504 100644
--- a/types/simple.test.tsx
+++ b/types/simple.test.tsx
@@ -69,6 +69,7 @@ import {
 // If custom variants or sizes are desired, cast to any
 <Button size="lg" variant={'custom' as any} />;
 <Button size={'custom' as any} variant="outline-warning" />;
+<Button size="lg" ref={(ref: HTMLButtonElement | null) => {}} />;
 
 <ButtonToolbar>
   <ButtonGroup size="lg">
```

3. Run `yarn dtslint`
4. See error (below)

<details>
<summary>TypeScript error</summary>

```
yarn run v1.19.1
$ dtslint types
Error: /Users/kumar/tmp/react-bootstrap/types/simple.test.tsx:72:19
ERROR: 72:19  expect  TypeScript@next compile error:
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ReplaceProps<"button", BsPrefixProps<"button"> & ButtonProps>>): Button<"button">', gave the following error.
    Type '(ref: HTMLButtonElement | null) => void' is not assignable to type '(string & ((instance: HTMLButtonElement | null) => void)) | (string & RefObject<HTMLButtonElement>) | (((instance: Button<"button"> | null) => void) & ((instance: HTMLButtonElement | null) => void)) | ... 4 more ... | undefined'.
      Type '(ref: HTMLButtonElement | null) => void' is not assignable to type 'string & ((instance: HTMLButtonElement | null) => void)'.
        Type '(ref: HTMLButtonElement | null) => void' is not assignable to type 'string'.
  Overload 2 of 2, '(props: ReplaceProps<"button", BsPrefixProps<"button"> & ButtonProps>, context?: any): Button<"button">', gave the following error.
    Type '(ref: HTMLButtonElement | null) => void' is not assignable to type '(string & ((instance: HTMLButtonElement | null) => void)) | (string & RefObject<HTMLButtonElement>) | (((instance: Button<"button"> | null) => void) & ((instance: HTMLButtonElement | null) => void)) | ... 4 more ... | undefined'.
      Type '(ref: HTMLButtonElement | null) => void' is not assignable to type 'string & ((instance: HTMLButtonElement | null) => void)'.
        Type '(ref: HTMLButtonElement | null) => void' is not assignable to type 'string'.

    at /Users/kumar/tmp/react-bootstrap/node_modules/dtslint/bin/index.js:190:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/kumar/tmp/react-bootstrap/node_modules/dtslint/bin/index.js:5:58)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

## Reproducible Example

(follow steps above)

## Expected behavior

There should be no TypeScript errors.

The example I gave should be a valid legacy ref, I think. I also tried setting it to a string ref and `React.createRef()` but they both produce errors.

## Environment (please complete the following information)

- Operating System: macOS
- Browser, Version: n/a
- React-Bootstrap Version: https://github.com/react-bootstrap/react-bootstrap/commit/68127cbe67338cdc24f83dc66f869f9bfc875aaa

## Additional context

This may be similar to https://github.com/react-bootstrap/react-bootstrap/issues/3805 or https://github.com/react-bootstrap/react-bootstrap/issues/3568 but I'm not sure.

**Comment by kosmiq** [comment]
This works for me when creating a ref for a button
`private button = React.createRef<HTMLButtonElement & Button>();`

And gives no errors. Tested it with
```
<Button ref={this.button} onClick={this.testFunction}>
  Test
</Button>
```

```
public resetPass = () => {
  console.log(this.button.current)
}
```

**Comment by kyletsang** [comment]
`ref = React.createRef<HTMLButtonElement>();` and `fn(e: HTMLButtonElement | null)` works on v1.1.1

Tested with TS 3.9.6
