### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by ma-nish** [react-bootstrap/react-bootstrap#5626]
## Reproducible Example

Minimal example by using [CodeSandbox](https://codesandbox.io/s/github/react-bootstrap/code-sandbox-examples/tree/master/basic).

## Environment (please complete the following information)

- Operating System: [e.g. macOS]
- Browser, Version [e.g. Chrome 74]
- React-Bootstrap Version [e.g. 1.0.0-beta.8]

## Additional context

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Transition (http://localhost:3000/0.34420fd5bcc5ec02bcbf.hot-update.js:2655:30)
    at Fade (http://localhost:3000/0.34420fd5bcc5ec02bcbf.hot-update.js:1013:24)
    at BackdropTransition
    at Modal (http://localhost:3000/0.34420fd5bcc5ec02bcbf.hot-update.js:1809:24)
    at Modal (http://localhost:3000/0.34420fd5bcc5ec02bcbf.hot-update.js:1122:23)
    at Login (http://localhost:3000/main.34420fd5bcc5ec02bcbf.hot-update.js:373:86)
    at Route (http://localhost:3000/static/js/0.chunk.js:43984:29)
    at Switch (http://localhost:3000/static/js/0.chunk.js:44186:29)
    at Router (http://localhost:3000/static/js/0.chunk.js:43619:30)
    at BrowserRouter (http://localhost:3000/static/js/0.chunk.js:43239:35)
    at App (http://localhost:3000/main.34420fd5bcc5ec02bcbf.hot-update.js:46:83)
    at Provider (http://localhost:3000/static/js/0.chunk.js:40855:20)

**Comment by jquense** [comment]
There are previous issues about this, please search for context and workarounds
