### ISSUE TITLE
TransitionWrapper - Check the render method of `Transition`.

### ISSUE THREAD

**Issue by JaysQubeXon** [react-bootstrap/react-bootstrap#6322]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

Hi `react-bootstrap` team,

First of thank you for your hard work.

I've recently upgraded a client of mine to react-bootstrap v2.3.1.

I am noticing the following error message in Chrome:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Transition`.
    at Item (https://localhost:44316/static/js/bundle.js:79359:5)
    at Transition (https://localhost:44316/static/js/bundle.js:197967:30)
    at https://localhost:44316/static/js/bundle.js:151479:5
    at div
    at div
    at https://localhost:44316/static/js/bundle.js:147480:70
    at Banner (https://localhost:44316/static/js/bundle.js:79347:5)
    at BannersContent (https://localhost:44316/static/js/bundle.js:11511:69)
    at ErrorBoundary (https://localhost:44316/static/js/bundle.js:47435:5)
    at I18nextWithTranslation (https://localhost:44316/static/js/bundle.js:180942:31)
    at <anonymous> (https://localhost:44316/static/js/bundle.js:51591:10)
    at div
    at https://localhost:44316/static/js/bundle.js:148104:5
    at div
    at LifeAndWork
    at ErrorBoundary (https://localhost:44316/static/js/bundle.js:47435:5)
    at I18nextWithTranslation (https://localhost:44316/static/js/bundle.js:180942:31)
    at Route (https://localhost:44316/static/js/bundle.js:192848:29)
    at Switch (https://localhost:44316/static/js/bundle.js:193050:29)
    at div
    at div
    at Layout (https://localhost:44316/static/js/bundle.js:7534:21)
    at App (https://localhost:44316/static/js/bundle.js:7080:84)
    at ActiveModalsProvider (https://localhost:44316/static/js/bundle.js:9828:5)
    at AppRoutesAndNavigationProvider (https://localhost:44316/static/js/bundle.js:7402:5)
    at BuildSession (https://localhost:44316/static/js/bundle.js:61429:69)
    at I18nextProvider (https://localhost:44316/static/js/bundle.js:180129:19)
    at Router (https://localhost:44316/static/js/bundle.js:192479:30)
    at HashRouter (https://localhost:44316/static/js/bundle.js:192146:35)
    at Provider (https://localhost:44316/static/js/bundle.js:189346:20)
    at FlagsProvider (https://localhost:44316/static/js/bundle.js:99827:28)
```
In Firefox:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Transition`.
Item@http://localhost:6006/main.iframe.bundle.js:1237:15
Transition@http://localhost:6006/vendors~main.iframe.bundle.js:149812:30
./node_modules/react-bootstrap/esm/TransitionWrapper.js/TransitionWrapper<@http://localhost:6006/vendors~main.iframe.bundle.js:121673:96
div
div
./node_modules/react-bootstrap/esm/Carousel.js/Carousel<@http://localhost:6006/vendors~main.iframe.bundle.js:120425:85
Banner@http://localhost:6006/main.iframe.bundle.js:1218:18
BannerStory
unboundStoryFn@http://localhost:6006/vendors~main.iframe.bundle.js:18397:30
ErrorBoundary@http://localhost:6006/vendors~main.iframe.bundle.js:31693:20
```

The carousel seems to be moving to the next item but then stops. In the example I've provided there are 4 items.

### Expected behavior

The carousel should continue through all items without errors.

### Reproducible Example

I've composed a skeleton version of the same Carousel implementation in [this codesnadbox.](https://codesandbox.io/s/epic-mccarthy-7o4n47?file=/src/App.js) to better illustrate the issue.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of React-Bootstrap are you using?

2.3.1

### What version of Bootstrap are you using?

5.1.3

**Comment by kyletsang** [comment]
The carousel children needs to be forward ref components.  This is needed to support strict mode with react-transition-group.  See modified sandbox:

https://codesandbox.io/s/nostalgic-alex-vlrdwl
