### ISSUE TITLE
TypeError: (0 , _css.default) is not a function

### ISSUE THREAD

**Issue by P4ul1029** [react-bootstrap/react-bootstrap#6346]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When I try testing the `Modal` component with the `show` prop I get the following error:

```
TypeError: (0 , _css.default) is not a function

      11 |   const placeholder = 'PlaceHolder Text';
      12 |   describe('Testing Modal exists', () => {
    > 13 |     const result = render(
         |                    ^
      14 |       <Modal show animation={false}>
      15 |         <div>test</div>
      16 |       </Modal>

      at BootstrapModalManager.setContainerStyle (node_modules/@restart/ui/cjs/ModalManager.js:64:57)
      at BootstrapModalManager.setContainerStyle (node_modules/react-bootstrap/cjs/BootstrapModalManager.js:48:11)
      at BootstrapModalManager.add (node_modules/@restart/ui/cjs/ModalManager.js:102:12)
      at Object.add (node_modules/@restart/ui/cjs/Modal.js:61:29)
      at Object.current (node_modules/@restart/ui/cjs/Modal.js:124:11)
      at node_modules/@restart/hooks/cjs/useEventCallback.js:15:39
      at node_modules/@restart/ui/cjs/Modal.js:163:5
      at invokePassiveEffectCreate (node_modules/react-dom/cjs/react-dom.development.js:23487:20)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:23574:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:23447:14)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:22269:3)
      at node_modules/react-dom/cjs/react-dom.development.js:11327:26
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:468:12)
      at runWithPriority$1 (node_modules/react-dom/cjs/react-dom.development.js:11276:10)
      at flushSyncCallbackQueueImpl (node_modules/react-dom/cjs/react-dom.development.js:11322:9)
      at flushSyncCallbackQueue (node_modules/react-dom/cjs/react-dom.development.js:11309:3)
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:22387:7)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1042:14)
      at render (node_modules/@testing-library/react/dist/pure.js:97:26)
      at src/components/Modal/Modal.test.tsx:13:20
      at src/components/Modal/Modal.test.tsx:12:3
      at Object.<anonymous> (src/components/Modal/Modal.test.tsx:10:1)
```

### Reproducible Example

Here is the code I ran in a _test.tsx_ file to produce the error:
```tsx
import React from 'react';
import { render } from '@testing-library/react';
import { Modal } from 'react-bootstrap';

describe('Modal Tests', () => {
  test('Testing Modal exists', () => {
    const result = render(
      <Modal show animation={false}>
        <div>test</div>
      </Modal>
    );
    expect(result).toBeTruthy();
  });
});
```

### What version of React-Bootstrap are you using?

2.1.1

### What version of Bootstrap are you using?

5.0.2

**Comment by kyletsang** [comment]
Can you post a full repro on code sandbox?

**Comment by P4ul1029** [comment]
> Can you post a full repro on code sandbox?

Here is the repo of the project I'm working on: https://github.com/ised-ocp-dev/wet-react/tree/share-widget-component
I ran into some errors importing it on Sandbox, but cloning it and running `npm run test` should be no issue.

I'm trying to test the [ShareWidget component](https://github.com/ised-ocp-dev/wet-react/blob/share-widget-component/src/components/ShareWidget/ShareWidget.tsx) I created that returns a bootstrap Modal component. When I pass the `show` prop in the [test file](https://github.com/ised-ocp-dev/wet-react/blob/share-widget-component/src/components/ShareWidget/ShareWidget.test.tsx), it produces the error above.

**Comment by kyletsang** [comment]
Were you able to resolve this?  I've tried copying some of your config into my tests and I don't see an error.   Also your repo code appears to be different from the example above.

**Comment by P4ul1029** [comment]
> Were you able to resolve this? I've tried copying some of your config into my tests and I don't see an error. Also your repo code appears to be different from the example above.

No, unfortunately I have not been able to resolve the issue yet. When you clone my repo and run `npm run test`, you do not get the error? The example I shared is just a simplified test of the one in my repo. Both test a Modal component that is using the `show` prop (`ShareWidget` returns a Modal component).

**Comment by kyletsang** [comment]
Sorry, turns out I was missing the show prop.  I can reproduce it and it appears to be due to 

```
moduleNameMapper: {
    '.(css|less|scss)$': 'identity-obj-proxy'
  },
```

The "css" in here is overriding a function called `css` that's used internally inside `dom-helpers`

Would using this work for you?

```
moduleNameMapper: {
    '\\.(css|less|scss)$': 'identity-obj-proxy'
  },
```

**Comment by P4ul1029** [comment]
> Sorry, turns out I was missing the show prop. I can reproduce it and it appears to be due to
> 
> ```
> moduleNameMapper: {
>     '.(css|less|scss)$': 'identity-obj-proxy'
>   },
> ```
> 
> The "css" in here is overriding a function called `css` that's used internally inside `dom-helpers`
> 
> Would using this work for you?
> 
> ```
> moduleNameMapper: {
>     '\\.(css|less|scss)$': 'identity-obj-proxy'
>   },
> ```

Thank you for the reply! I'll try out this solution and test to see if causes any problems. I'll close the issue, but if I ran into anymore related problems I'll let you know on this thread.
