### ISSUE TITLE
Rendering `<Offcanvas/>` in tests causes an error and fails the test

### ISSUE THREAD

**Issue by dantabel** [react-bootstrap/react-bootstrap#6426]
### Prerequisites

- [X] I am using the [correct version](https://github.com/react-bootstrap/react-bootstrap#bootstrap-compatibility) of React-Bootstrap for my version of Bootstrap
- [X] I have [searched](https://github.com/react-bootstrap/react-bootstrap/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/react-bootstrap/react-bootstrap/blob/master/CONTRIBUTING.md)

### Describe the bug

When writing tests for components that contain `<Offcanvas/>` all tests fail with the error message:
```
TypeError: targetWindow.matchMedia is not a function
```

Full trace in the screenshot below.

Reverting back to `react-bootstrap@~2.4.0` and `bootstrap@~5.1.0` resolves the issue.

### Expected behavior

Expect the tests to pass and not produce an error.

### To Reproduce

1. Create a React component containing `<Offcanvas/>` in the output.
2. Create a test file that renders the component you just created.
3. Run `npm run test` or `yarn test`.

### Reproducible Example

The link below is a fork from the link above with [Offcanvas Basic Example](https://react-bootstrap.github.io/components/offcanvas/#basic-example) from the docs. I have updated all dependencies to the latest versions to replicate the issue.

https://codesandbox.io/s/hopeful-https-3qt3nd?file=/src/App.js

### Screenshots

```
targetWindow.matchMedia is not a function

TypeError: targetWindow.matchMedia is not a function
    at getMatcher (https://3qt3nd.csb.app/node_modules/@restart/hooks/esm/useMediaQuery.js:15:24)
    at useMediaQuery (https://3qt3nd.csb.app/node_modules/@restart/hooks/esm/useMediaQuery.js:25:13)
    at useBreakpoint (https://3qt3nd.csb.app/node_modules/@restart/hooks/esm/useBreakpoint.js:57:38)
    at eval (https://3qt3nd.csb.app/node_modules/react-bootstrap/esm/Offcanvas.js:62:61)
    at renderWithHooks (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:16305:18)
    at updateForwardRef (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:19226:20)
    at beginWork (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:21636:16)
    at beginWork$1 (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27426:14)
    at performUnitOfWork (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26557:12)
    at workLoopSync (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26466:5)
    at renderRootSync (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26434:7)
    at performSyncWorkOnRoot (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26085:20)
    at flushSyncCallbacks (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:12042:22)
    at flushSync (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:26201:7)
    at legacyCreateRootFromDOMContainer (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:29575:5)
    at legacyRenderSubtreeIntoContainer (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:29601:12)
    at Object.render (https://3qt3nd.csb.app/node_modules/react-dom/cjs/react-dom.development.js:29685:10)
    at Object.eval (https://3qt3nd.csb.app/src/App.test.js:17:21)
    at https://codesandbox.io/static/js/3.c68bd71c0.chunk.js:1:336366
    at new Promise (<anonymous>)
    at t.callAsyncFn (https://codesandbox.io/static/js/3.c68bd71c0.chunk.js:1:336025)
    at https://codesandbox.io/static/js/7.cdfc7986d.chunk.js:1:6524
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:357
    at https://codesandbox.io/static/js/7.cdfc7986d.chunk.js:1:6791
    at https://codesandbox.io/static/js/7.cdfc7986d.chunk.js:1:5456
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:357
    at https://codesandbox.io/static/js/7.cdfc7986d.chunk.js:1:5814
    at https://codesandbox.io/static/js/7.cdfc7986d.chunk.js:1:4116
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3629)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3382)
    at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:3986)
    at r (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:206)
    at u (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.bcc15d438.chunk.js:1:417)
```

### What operating system(s) are you seeing the problem on?

Windows, macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of React-Bootstrap are you using?

2.5.0

### What version of Bootstrap are you using?

5.2.0

**Comment by golota60** [comment]
hey, thanks for the issue - this issue is actually related to jest([which cra uses](https://create-react-app.dev/docs/running-tests#testing-components)) and it's got a solution for it - https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom
![image](https://user-images.githubusercontent.com/37072867/191222935-21d32028-e24a-4673-ae76-cc42e18e4fe1.png)


Also it seems to be resolved when using React 18's `createRoot`.
e.g.
```ts
it("renders without crashing", () => {
  const div = document.createElement("div");
  const root = ReactDOM.createRoot(div);
  root.render(<App />);
  root.unmount();
});

```
