### ISSUE TITLE
Tab & Tabs Not Working: node2.addEventListener

### ISSUE THREAD

**Issue by ynwd** [react-bootstrap/react-bootstrap#6697]
SSR App. Build with [ESBUILD](https://esbuild.github.io/) and Deno.

import_map.json
```
{
  "imports": {
    "react/": "https://esm.sh/v132/react@18.2.0/",
    "react-dom": "https://esm.sh/v132/react-dom@18.2.0",
    "react-dom/": "https://esm.sh/v132/react-dom@18.2.0/",
    "prismjs/": "https://esm.sh/v132/prismjs@1.29.0/",
    "react": "https://esm.sh/v132/react@18.2.0?dev",
    "react-bootstrap-button": "https://esm.sh/v132/react-bootstrap@2.9.0/Button?dev",
    "react-bootstrap-modal": "https://esm.sh/v132/react-bootstrap@2.9.0/Modal?dev",
    "react-bootstrap-tabs": "https://esm.sh/v132/react-bootstrap@2.9.0/Tabs?dev",
    "react-bootstrap-tab": "https://esm.sh/v132/react-bootstrap@2.9.0/Tab?dev"
  }
}
```

```tsx
import React from "react";
import Tabs from "react-bootstrap-tabs";
import Tab from "react-bootstrap-tab";

export function HashView() {
  return (
    <Tabs
      defaultActiveKey="profile"
      id="uncontrolled-tab-example"
      className="mb-3"
    >
      <Tab eventKey="home" title="Home">
        Tab content for Home
      </Tab>
      <Tab eventKey="profile" title="Profile">
        Tab content for Profile
      </Tab>
    </Tabs>
  );
}

```

```
Uncaught TypeError: node2.addEventListener is not a function
    at addEventListener (uuid.js:152:14292)
    at Object.invokeGuardedCallbackImpl (uuid.js:31:43159)
    at invokeGuardedCallback (uuid.js:31:44603)
    at invokeGuardedCallbackAndCatchFirstError (uuid.js:31:44736)
    at executeDispatch (uuid.js:31:119141)
    at processDispatchQueueItemsInOrder (uuid.js:31:120017)
    at processDispatchQueue (uuid.js:31:120354)
    at dispatchEventsForPlugins (uuid.js:31:120713)
    at uuid.js:31:124749
    at batchedUpdates$1 (uuid.js:111:48541)
```

<img width="847" alt="Screenshot 2023-09-29 at 09 55 46" src="https://github.com/react-bootstrap/react-bootstrap/assets/10122431/d690eaa9-3ed4-43c1-949e-aaf2a662a317">

**Comment by bigkho** [comment]
I would like to point out that the dependency in question is not React Bootstrap, but specifically react-bootstrap-tabs. You can find that library [here](https://github.com/freeranger/react-bootstrap-tabs). You may need to open the issue there itself.

**Comment by ynwd** [comment]
please not that : `react-bootstrap-tab` ---> https://esm.sh/v132/react-bootstrap@2.9.0/Tab?de

```
"react-bootstrap-tab": "https://esm.sh/v132/react-bootstrap@2.9.0/Tab?dev"
```
